### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by manstfu** [jose-donato/race-stack#3]
After succesfully creating an account, when i log in i get the following error:

`POST /login?_data=routes%2Flogin 204 No Content (55.65ms)`

`
Response {
  [Symbol(realm)]: { settingsObject: {} },
  [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: false,
    requestIncludesCredentials: false,
    type: 'default',
    status: 401,
    timingInfo: null,
    cacheState: '',
    statusText: '',
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    },
    urlList: [],
    body: {
      stream: undefined,
      source: '{"message":"Invalid email or password"}',
      length: 39
    }
  },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(1) { 'content-type' => [Object] },
    [Symbol(headers map sorted)]: null
  }
}
`

**Comment by jose-donato** [comment]
Hey sorry for the delay. 

Does it work for you now?
